services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - vendas-network

  nginx:
      image: nginx:alpine
      ports:
          - "80:80"
          - "8080:8080" # Mantemos para o seu HMR (v-dev)
      volumes:
          - .:/var/www
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - app
      networks:
          - vendas-network

  db:
    image: mysql:8.0
    container_name: vendas-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vendas_db
      MYSQL_ROOT_PASSWORD: vendas
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vendas-network

networks:
  vendas-network:
    driver: bridge

volumes:
  db_data:
